### ISSUE TITLE
Apply decorrelation to AVIRIS plastic detection

### ISSUE THREAD

**Issue by pomadchin** [azavea/nasa-hyperspectral#112] opened 2021-02-19 17:11 UTC

**Comment by jpolchlo** [comment] 2021-05-04 17:38
This issue was intended to push the results from #111 to AVIRIS for the purposes of plastic detection.  The notebook submitted with #116 showed that this approach does not work as advertised.  In some sense, this issue was addressed by #116, but in either event, this issue is concluded.

**Closed by jpolchlo** 2021-05-04 17:38 UTC
Labels: blocked
